[features]
seeds = false
skip-lint = false
[programs.devnet]
gifportal = "3iYPHRpMGesfBiYLS7pBWnhsXoywdYhMKh7ys5x9cLtU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/apple/.config/solana/id.json"

[scripts]
test = "node tests/gifportal.js"
